package bean;
// Generated Dec 14, 2024 5:12:36 PM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Vendas generated by hbm2java
 */
@Entity
@Table(name="vendas"
    ,catalog="db_matheuscosta"
)
public class Vendas  implements java.io.Serializable {


     private int idvendas;
     private Integer clienteId;
     private Integer albumId;
     private Date dataVenda;
     private Integer quantidade;
     private BigDecimal valorTotal;
     private String status;

    public Vendas() {
    }

	
    public Vendas(int idvendas) {
        this.idvendas = idvendas;
    }
    public Vendas(int idvendas, Integer clienteId, Integer albumId, Date dataVenda, Integer quantidade, BigDecimal valorTotal, String status) {
       this.idvendas = idvendas;
       this.clienteId = clienteId;
       this.albumId = albumId;
       this.dataVenda = dataVenda;
       this.quantidade = quantidade;
       this.valorTotal = valorTotal;
       this.status = status;
    }
   
     @Id 

    
    @Column(name="idvendas", unique=true, nullable=false)
    public int getIdvendas() {
        return this.idvendas;
    }
    
    public void setIdvendas(int idvendas) {
        this.idvendas = idvendas;
    }

    
    @Column(name="cliente_id")
    public Integer getClienteId() {
        return this.clienteId;
    }
    
    public void setClienteId(Integer clienteId) {
        this.clienteId = clienteId;
    }

    
    @Column(name="album_id")
    public Integer getAlbumId() {
        return this.albumId;
    }
    
    public void setAlbumId(Integer albumId) {
        this.albumId = albumId;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="data_venda", length=19)
    public Date getDataVenda() {
        return this.dataVenda;
    }
    
    public void setDataVenda(Date dataVenda) {
        this.dataVenda = dataVenda;
    }

    
    @Column(name="quantidade")
    public Integer getQuantidade() {
        return this.quantidade;
    }
    
    public void setQuantidade(Integer quantidade) {
        this.quantidade = quantidade;
    }

    
    @Column(name="valor_total", precision=10)
    public BigDecimal getValorTotal() {
        return this.valorTotal;
    }
    
    public void setValorTotal(BigDecimal valorTotal) {
        this.valorTotal = valorTotal;
    }

    
    @Column(name="status", length=9)
    public String getStatus() {
        return this.status;
    }
    
    public void setStatus(String status) {
        this.status = status;
    }




}


